# Generated by Django 3.1.4 on 2021-05-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careType', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('dateOfAppointment', models.CharField(max_length=50)),
                ('timeOfAppoinment', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('Status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
